server:
  port: 8082
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  datasource:
    url: jdbc:mysql://ukyqpzftq2xqkeqx:e7eMfZNmNdpbYZaSpcGF@bylsdzw6xlxwgw6veams-mysql.services.clever-cloud.com:3306/bylsdzw6xlxwgw6veams
    username: ukyqpzftq2xqkeqx
    password: e7eMfZNmNdpbYZaSpcGF
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa: 
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true